<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post view template
 *
 * @var $block \Magefan\Blog\Block\Post\View
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);

    $imageHelper = $this->helper('Magefan\Blog\Helper\Image');
    $imageWidth = 500;
    $imageHeight = 200;
?>
<div class="post-view">
    <div class="post-holder post-holder-<?php echo $_post->getId() ?>">
        <div class="post-content">
            <div class="post-description clearfix">
            <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                    <?php
                        $featuredImgAlt = $_post->getData('featured_img_alt');
                        if (!$featuredImgAlt) {
                            $featuredImgAlt = $_postName;
                        }
                    ?>
                    <div class="post-ftimg-hld">
                    <amp-img layout="responsive" src="<?= $block->escapeUrl($featuredImage) ?>"
                             alt="<?= $block->escapeHtml($featuredImgAlt) ?>">
                    </amp-img>
                    </div>
                <?php } ?>
               
                <div class="post-text-hld">
                    <?php echo $block->getContent() ?>
                    <div class="blogpoststaticblock">
                    <?php echo $this->getLayout() ->createBlock('Magento\Cms\Block\Block')->setBlockId('block-post-static-block') ->toHtml();?>

                       
                    </div>
                   
                    <div class="clear"></div>
                </div>
                
            </div>
        </div>

        <div class="post-bottom">
            <?php echo $this->getChildHtml('blog.post.bottom') ?>
        </div>
    </div>
</div>
    <script id="blogstaticblock" type="text/plain" target="amp-script">        
        require(["jquery"], function($){
            $(".blogpoststaticblock").insertAfter( $(".post-text-hld p:nth-child(2)"));
        });
        
    </script>

   


