<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Amp
 * @copyright   Copyright (c) 2016 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')): ?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items">
            <amp-accordion id="product-data-tabs">
                <?php /* Sorting group elements by name before rendering */ sort($detailedInfoGroup) ?>
                <?php foreach ($detailedInfoGroup as $key => $name):?>
                    <?php
                        $html = $layout->renderElement($name);
                        if (!trim($html)) {
                            continue;
                        }
                        $alias = $layout->getElementAlias($name);
                        $label = $block->getChildData($alias, 'title');
                        $alias = str_replace('.', '-', $alias);
                    ?>
                    <section <?php echo ($key == 0) ? "expanded" : "" ?> id="section-<?php /* @escapeNotVerified */ echo $alias; ?>">
                        <header class="items-block-heading"><?php /* @escapeNotVerified */ echo $label; ?></header>
                        <div class="tab-content" id="<?php /* @escapeNotVerified */ echo $alias; ?>">
                            <?php /* @escapeNotVerified */ echo $html; ?>
                        </div>
                    </section>
                <?php endforeach;?>
            </amp-accordion>
        </div>
    </div>
<?php endif; ?>










<?php

$product = $block->getProduct();
$moment = $product->getAttributeText('moment_select');

?>


<div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items">
            <amp-accordion id="product-data-tabs-2">
            

                    <section expanded="" id="section-amp-product-info-description">
                        <header class="items-block-heading i-amphtml-accordion-header" role="button" aria-controls="amp-product-info-description" aria-expanded="true" tabindex="0">Description</header>
                        <div class="tab-content i-amphtml-accordion-content" id="amp-product-info-description2">
                            
<div class="product attribute description">
    <strong class="type"></strong>    <div class="value"><?php echo $product->getData('description'); ?></div>
</div>
                        </div>
                    </section>




                    <section expanded="" id="section-amp-product-info-testimonials">
                        <header class="items-block-heading i-amphtml-accordion-header" role="button" aria-controls="amp-product-info-description" aria-expanded="false" tabindex="0">Testimonials</header>
                        <div class="tab-content i-amphtml-accordion-content" id="amp-product-info-
">
                            
<div class="product attribute description">
    <strong class="type"></strong>    <div class="value"><?php
if (!empty($product->getData('testimonial_quote_1'))) {?>
    <p class="testimonial-quote">"<?php echo $product->getData('testimonial_quote_1'); ?>" - <span class="testimonial-author"><?php echo $product->getData('testimonial_author_1'); ?></span></p>
<?php } 
if (!empty($product->getData('testimonial_quote_2'))) {?>
    <p class="testimonial-quote">"<?php echo $product->getData('testimonial_quote_2'); ?>" - <span class="testimonial-author"><?php echo $product->getData('testimonial_author_2'); ?></span></p>
    <?php } 
    if (!empty($product->getData('testimonial_quote_3'))) {?>
    <p class="testimonial-quote">"<?php echo $product->getData('testimonial_quote_3'); ?>" - <span class="testimonial-author"><?php echo $product->getData('testimonial_author_3'); ?></span></p>
    <?php } 
    if (!empty($product->getData('testimonial_quote_4'))) {?>
    <p class="testimonial-quote">"<?php echo $product->getData('testimonial_quote_4'); ?>" - <span class="testimonial-author"><?php echo $product->getData('testimonial_author_4'); ?></span></p>
    <?php } ?></div>
</div>
                        </div>
                    </section>

                    </div>
                    </div>







