

        


<div class="col product-share">
 
                             
 <ul class="social-network social-circle">
                        <!--li><a href="#" class="icoRss" title="Rss"><i class="fa fa-instagram"></i></a></li>-->
                   <li><a href="https://www.facebook.com/sharer/sharer.php?u=&t=" title="Share on Facebook" target="_blank" onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=' + encodeURIComponent(document.URL) + '&t=' + encodeURIComponent(document.URL)); return false;"   class="icoFacebook" ><i class="fa fa-facebook"></i></a></li>
                       
                           <li><a href="http://www.linkedin.com/shareArticle?mini=true&url=&title=&summary=&source=" target="_blank" title="Share on LinkedIn" onclick="window.open('http://www.linkedin.com/shareArticle?mini=true&url=' + encodeURIComponent(document.URL) + '&title=' + encodeURIComponent(document.title)); return false;" class="icoLinkedin" ><i class="fa fa-linkedin"></i></a></li>
                        <li><a title="Share on Twitter" class="icoTwitter"  onclick="window.open('https://twitter.com/intent/tweet?url=' + encodeURIComponent(document.URL) + '&t=' + encodeURIComponent(document.URL)); return false;" >
                              <i class="fa fa-twitter"></i></a></li>
                    </ul>	
        
   
  </div>
