<?php
// @codingStandardsIgnoreFile
?>
<div class="block discount giftcard-discount" id="block-discount"
    data-mage-init='{"collapsible":{"openedState": "active", "saveState": false}}'>
    <div class="title" data-role="title">
        <strong id="block-discount-heading" role="heading" aria-level="2">
            <?php /* @escapeNotVerified */ /* @noEscape */ echo __('Apply Gift Code') ?>
        </strong>
    </div>
    <div class="content" data-role="content" aria-labelledby="block-discount-heading">
        <form id="giftcard-discount-coupon-form" giftcard-discount
              action="<?php /* @escapeNotVerified */ /* @noEscape */ echo $block->getUrl('giftcard/checkout/giftcodePost') ?>"
              method="post"
              data-mage-init='{"giftcode":{"couponCodeSelector": "#giftcode",
                                               "removeCouponSelector": "#remove-giftcard-coupon",
                                               "applyButton": "button.action.apply_giftcode",
                                               "cancelButton": "button.action.cancel_giftcode"}}'>
            <div class="fieldset coupon<?php strlen($block->getGiftcode()) ? ' applied' : ''?>">
                <input type="hidden" name="remove" id="remove-giftcard-coupon" value="0" />
                <div class="field">
                    <label for="giftcode" class="label">
                        <span><?php /* @escapeNotVerified */ /* @noEscape */ echo __('Enter discount code') ?></span>
                    </label>
                    <div class="control">
                        <input type="text" class="input-text" id="giftcode" name="giftcode"
                        value="<?php /* @noEscape */ echo $block->escapeHtml($block->getGiftcode()) ?>"
                        placeholder="<?php /* @noEscape */ echo $block->escapeHtml(__('Enter discount code'));?>" />
                    </div>
                </div>
                <div class="actions-toolbar">
                    <?php if (!strlen($block->getGiftcode())) : ?>
                    <div class="primary">
                        <button class="action apply_giftcode primary" type="button"
                        value="<?php /* @escapeNotVerified */ /* @noEscape */ echo __('Apply Gift Code') ?>">
                            <span><?php /* @escapeNotVerified */ /* @noEscape */ echo __('Apply Gift Code') ?></span>
                        </button>
                    </div>
                    <?php else : ?>
                        <div class="primary">
                            <button  type="button" class="action cancel_giftcode primary"
                            value="<?php /* @escapeNotVerified */ /* @noEscape */ echo __('Cancel Gift Code') ?>">
                            <span><?php /* @escapeNotVerified */ /* @noEscape */ echo __('Cancel Gift Code') ?></span>
                            </button>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </form>
    </div>
</div>
