<div class="entry-edit form-inline">
    <form>
		<div></div>
		<fieldset id="guide_general_fieldset" class="fieldset admin__fieldset guide-fieldset">
			<legend class="admin__legend legend">
                <span>General Instructions</span>
            </legend><br>

			<div class="messages"></div>
        
			<div class="fieldset ">
				Magento Gift Card extension allows to send gift code to customers:<br><br>
				<strong>1. Gift Code Pattern</strong>
				<br>
					{L} - letter, {D} - digit<br>
					e.g. PROMO_{L}{L}{D}{D}{D} results in PROMO_NS035
					<br><br>
				<strong>2. Cron Jobs</strong>
				<br>
					Please setup cron jobs to smoothly run giftcard extension, because giftcard extension uses cron jobs
				<br><br>
				<strong>3. When a gift code get generated?</strong>
				<br>
					Once invoice is generated for order then a gift code will be generated for gift card product.
				<br>
				
			</div>

		</fieldset>
	</form>
</div>