<main>
            
            <section class="landing-product">
              <div class="container-fluid">
                    <div class="row  standard-half-bottom">
                       <div class="col-sm-12 uppercase-copy" style="text-align:center">
                        <h1>OTO Essential Oil Roll Ons - 20% CBD</h1>
                 
                        

                       </div>
                    </div>
                    <div class="full row standard" style="max-width:1440px;margin-left:auto;margin-right:auto;">
                        <div class="col-lg-4 ">
                            <div class="product-grid7">
                                <div class="product-image7" style="max-height:250px">
                                    <a href="https://otocbd.com/focus-20-percent-cbd-essential-oil.html">
										

                              <img src="https://otocbd.com/pub/media/focus-250.jpg" alt="" />
                                    </a>
                                    
                                
                                </div>
              <div class="product-content focus" >             
                                    <h3 class="title focus"><a href="focus-20-percent-cbd-essential-oil.html">Focus 20% CBD</a></h3>
     
<div class="price">£109
                                       
                                    </div>
                    
 <p style="padding:5px;text-align:left"><span style='font-weight:bold'>Essential ingredients: </span>Ylang Ylang, Peppermint and Rosemary</p>
                                    
                                        <div class="link-box-main-button">
                                    

  <?php
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $product = $objectManager->get('Magento\Catalog\Model\Product')->load(1);
            $listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');
            $addToCartUrl =  $listBlock->getAddToCartUrl($product);
        ?>
        <form data-role="tocart-form" action="<?php echo $addToCartUrl; ?>" method="post">
            <?php echo $block->getBlockHtml('formkey')?>
            <button type="submit" title="Add to Cart" class="button-round-black-border" type="submit" style="color: #026974;border-color:#026974">
        Add to Cart
            </button>
        </form>



</div>

                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 ">
                            <div class="product-grid7">
                                <div class="product-image7" style="max-height:250px">
                                    <a href="amplify.html">
										  <img  src="https://otocbd.com/pub/media/amplify-250.jpg" alt="OTO CBD Amplify Essential Oils">
                            
                                    </a>
                                    
                                </div>
                                <div class="product-content amplify">
                                    <h3 class="title amplify"><a href="amplify-20-percent-cbd-essential-oil.html">Amplify 20% CBD</a></h3>
                                   
                                    <div class="price">£109</div>
                          
 <p style="padding:5px;text-align:left"><span style='font-weight:bold'>Essential ingredients: </span>Bitter Orange, Bergamot, Sandalwood</p>
                                    
                                        <div class="link-box-main-button">
                                 
									<button class="butto   <form method="link" action="https://otocbd.com/checkout/cart/add/uenc/aHR0cHM6Ly9vdG9jYmQuY29tL3Nob3AuaHRtbA%2C%2C/product/2/">n-round-black-border" type="submit" style="color: #ff3e14;;border-color:#ff3e14;">Find out more</button>
									</form></div>

                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 ">
                            <div class="product-grid7">
                                <div class="product-image7" style="max-height:250px">
                                    <a href="balance-20-percent-cbd-essential-oil.html">
										<img  src="https://otocbd.com/pub/media/balance-250.jpg" alt="OTO CBD Balance Essential Oils">
                           
                                    </a>
                                 
                                </div>
                                <div class="product-content balance">
                                    <h3 class="title balance"><a href="balance-20-percent-cbd-essential-oil.html">Balance 20% CBD</a></h3>
                                   
                                    <div class="price">£109
                                        
                                    </div>

                            
 <p style="padding:5px;text-align:left">Help get relaxed and find your calm </p>
                                    
                                        <div class="link-box-main-button">
                                    <form method="link" action="https://otocbd.com/checkout/cart/add/uenc/aHR0cHM6Ly9vdG9jYmQuY29tL3Nob3AuaHRtbA%2C%2C/product/3/">
									<button class="button-round-black-border" type="submit" style="color: #874680;border-color:#874680">Find out more</button>
									</form></div>

                                    
                                 
</div>
                                </div>
                            </div>
                        </div>
                    
                   



                


                
</div>
            </section>



            <section class="landing-product">
              <div class="container-fluid">
                    <div class="row  standard-half-bottom">
                       <div class="col-sm-12 uppercase-copy" style="text-align:center">
                        <h1>OTO Pillow Mist - 30% CBD</h1>
                 
                 
                        

                       </div>
                    </div>
                    <div class="full row standard" style="max-width:1440px;margin-left:auto;margin-right:auto;">
                        <div class="col-lg-4 ">
                         </div>
                        <div class="col-lg-4 ">
                            <div class="product-grid7">
                                <div class="product-image7" style="max-height:250px">
                                    <a href="https://otocbd.com/oto-cbd-pillow-mist.html">
										  <img src="{{view url='images/pillow-mist-250.jpg'}}"  alt="OTO Pillow Mist 30 percent CBD"/>
                            
                                    </a>
                                    
                                </div>
                                <div class="product-content amplify">
                                    <h3 class="title balance"><a href="https://otocbd.com/oto-cbd-pillow-mist.html">OTO Pillow Mist - 30% CBD</a></h3>
                          
                                    <div class="price">£109</div>
                       
 <p style="padding:5px;text-align:left">Specialy created to promote a good night's sleep and to feel fresh in the morning.</p>
                                    
                                        <div class="link-box-main-button">
                                    <form method="link" action="amplify-20-percent-cbd-essential-oil.html">
									<button class="button-round-black-border" type="submit" style="color: #ff3e14;;border-color:#ff3e14;">Find out more</button>
									</form></div>

                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 ">
                        </div>
                    
                   



                


                
</div>
            </section>




            <section class="landing-product">
              <div class="container-fluid">
                    <div class="row  standard-half-bottom">
                       <div class="col-sm-12 uppercase-copy" style="text-align:center">
                        <h1>OTO CBD Ready to Drink Shots</h1>
                 
                        <p>The worlds most powerful CBD Shots</p>
                        

                       </div>
                    </div>
                    <div class="full row standard" style="max-width:1440px;margin-left:auto;margin-right:auto;">
                        <div class="col-lg-4 ">
                            <div class="product-grid7">
                                <div class="product-image7" style="max-height:250px">
                                    <a href="https://otocbd.com/oto-cbd-shots.html#sfocus">
										

                         <img src="{{view url='images/focus-spice-250.jpg'}}"  alt="OTO Focus Spice CBD Shot"/>
                                    </a>
                                    
                                
                                </div>
              <div class="product-content focus" >             
                                    <h3 class="title focus"><a href="https://otocbd.com/oto-cbd-shots.html#sfocus">Focus</a></h3>
       <h3 class="title focus sub"><a href="https://otocbd.com/oto-cbd-shots.html#sfocus">Spice</a></h3>
<div class="price">£109
                                       
                                    </div>
                                   
 <p style="padding:5px;text-align:left"><span style='font-weight:bold'>Designed to enhance concentration and help users stay relaxed and engaged</p>
                                    
                                        <div class="link-box-main-button">
                                    <form method="link" action="https://otocbd.com/become-a-stockist">
									<button class="button-round-black-border" type="submit" style="color: #026974;border-color:#026974">Become a stockist</button>
									</form>
</div>

                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 ">
                            <div class="product-grid7">
                                <div class="product-image7" style="max-height:250px">
                                    <a href="https://otocbd.com/oto-cbd-shots.html#samplify">
										  <img src="{{view url='images/amplify-zest-250.jpg'}}"  alt="OTO Amplify Zest CBD Shot"/>
                            
                                    </a>
                                    
                                </div>
                                <div class="product-content amplify">
                                    <h3 class="title amplify"><a href="https://otocbd.com/oto-cbd-shots.html#samplify">Amplify</a></h3>
                                   <h3 class="title amplify"><a href="https://otocbd.com/oto-cbd-shots.html#samplify">Zest</a></h3>
                                    <div class="price">£109</div>
                       
 <p style="padding:5px;text-align:left">Designed to help you unwind and feel your very best when out and about</p>
                                    
                                        <div class="link-box-main-button">
                                    <form method="link" action="https://otocbd.com/become-a-stockist">
									<button class="button-round-black-border" type="submit" style="color: #ff3e14;;border-color:#ff3e14;">Become a stockist</button>
									</form></div>

                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 ">
                            <div class="product-grid7">
                                <div class="product-image7" style="max-height:250px">
                                    <a href="https://otocbd.com/oto-cbd-shots.html#sbalance">
										  <img src="{{view url='images/balance-bloom-250.jpg'}}"  alt="OTO Balance Bloom CBD Shot"/>
<img src="{{view url='images/balance-bloom-250.jpg'}}"  alt="OTO Balance Bloom CBD Shot"/>
                           
                                    </a>
                                 
                                </div>
                                <div class="product-content balance">
                                    <h3 class="title balance"><a href="https://otocbd.com/oto-cbd-shots.html#sbalance">Balance</a></h3>
<h3 class="title balance"><a href="https://otocbd.com/oto-cbd-shots.html#sbalance">Bloom</a></h3>
                                   
                                    <div class="price">£109
                                        
                                    </div>

                   
 <p style="padding:5px;text-align:left">Designed to promote calm and balance throughout the day and into the night</p>
                                    
                                        <div class="link-box-main-button">
                                    <form method="link" action="https://otocbd.com/become-a-stockist">
									<button class="button-round-black-border" type="submit" style="color: #874680;border-color:#874680">Become a stockist</button>
									</form></div>

                                    
                                 
</div>
                                </div>
                            </div>
                        </div>
                    
                   



                


                
</div>
            </section>


 <section class="landing-product">
              <div class="container-fluid">
                    <div class="row  standard-half-bottom">
                       <div class="col-sm-12 uppercase-copy" style="text-align:center">
                        <h1>OTO CBD Bitters</h1>
                 
                        <p>Add to tonic, water or cocktails</p>
                        

                       </div>
                    </div>
                    <div class="full row standard" style="max-width:1440px;margin-left:auto;margin-right:auto;">
                        <div class="col-lg-4 ">
                         </div>
                        <div class="col-lg-4 ">
                            <div class="product-grid7">
                                <div class="product-image7" style="max-height:250px">
                                    <a href="amplify.html">
<img src="{{view url='images/bitters-250.jpg'}}"  alt="OTO CBD Bitters"/>
										
                            
                                    </a>
                                    
                                </div>
                                <div class="product-content amplify">
                                    <h3 class="title amplify"><a href="amplify-20-percent-cbd-essential-oil.html">OTO CBD Bitters</a></h3>
                                   
                                    <div class="price">£98</div>
                       
 <p style="padding:5px;text-align:left">Connect with yourself and with others</p>
                                    
                                        <div class="link-box-main-button">
                                    <form method="link" action="amplify-20-percent-cbd-essential-oil.html">
									<button class="button-round-black-border" type="submit" style="color: #ff3e14;;border-color:#ff3e14;">Find out more</button>
									</form></div>

                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 ">
                        </div>
                    
                   



                


                
</div>
            </section>

<section>

<div id="testimonial" class="carousel slide pillow-mist carousel-fade" data-ride="carousel" data-interval="7000" style="padding-top:0;padding-bottom:0">

 
 
  <!-- The slideshow -->
  <div class="carousel-inner">
    <div class="carousel-item active">
          <div class=" d-flex flex-column h-100 align-items-center justify-content-center">
     <blockquote>I noticed I was sleeping better and I was feeling more relaxed.-</blockquote>
        <p class="user">Cora K</p>
     </div>
    </div>
    <div class="carousel-item">
          <div class="d-flex flex-column h-100 align-items-center justify-content-center">
     <blockquote>Calming, less stressed, sleeping better, less tension in shoulder muscles.</blockquote>
         <p class="user">Angela M</p>
              </div>
    </div>
    <div class="carousel-item">
          <div class="d-flex flex-column h-100 align-items-center justify-content-center">
        <blockquote>Definitely gives an almost instant effect of focus. Great for work. After a few
days I felt noticeably more positive.</blockquote>
       <p class="user">Oli H</p>
              </div>
      
    </div>
      <div class="carousel-item">
            <div class=" d-flex flex-column h-100 align-items-center justify-content-center">
       <blockquote>I felt a lot more relaxed and less anxious after the first week. I also found
myself sleeping better.</blockquote>
           <p class="user"> Mazzy-Mae G</p>
                </div>
    </div>
      <div class="carousel-item">
            <div class="d-flex flex-column h-100 align-items-center justify-content-center">
    <blockquote> There was a notable improvement to my focus and i genuinely felt much
more relaxed and calm.</blockquote>
           <p class="user"> Kieron E</p>

</div>
    </div>
       <div class="carousel-item">
            <div class=" d-flex flex-column h-100 align-items-center justify-content-center">
     <blockquote>‘ really enjoyed using it, even the ritual made me feel motivated</blockquote>
          <p class="user"> Emma M</p>
                </div>
    </div>
      <div class="carousel-item">
        <div class="d-flex flex-column h-100 align-items-center justify-content-center">
<blockquote>I didn't find myself getting overwhelmed in stressful situations.</blockquote>
           <p class="user"> Ian S</p>
            </div>
    </div>
      <div class="carousel-item">
        <div class=" d-flex flex-column h-100 align-items-center justify-content-center">
<blockquote>I have definitely been sleeping better, and felt more calm.</blockquote>
           <p class="user">Steph H</p>
            </div>
    </div>
     
  </div>
    
   
  
  <!-- Left and right controls -->
  <a class="carousel-control-prev" data-target="#testimonial" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" data-target="#testimonial" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>
</div>
    
    </section>




              

<script>

require([ 'jquery' ,  'domReady!'],function($){

  function isScrolledIntoView(elem) {
    var docViewTop = $(window).scrollTop();
    var docViewBottom = docViewTop + $(window).height();

    var elemTop = $(elem).offset().top;
    var elemBottom = elemTop + $(elem).height();

    return ((elemBottom <= docViewBottom) && (elemTop >= docViewTop));
}

$(window).scroll(function () {
    $('.animate-now').each(function () {
        if (isScrolledIntoView(this) === true) {
            $(this).addClass('progress-bar')
        }
    });

});
});

</script> 

</main>