<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500&display=swap');

.post-holder {padding-bottom: 20px;  margin-bottom: 20px; background: #F9F9F9; padding: 20px}
.post-holder:hover {box-shadow: 3px 3px 4px 0 rgba(0, 0, 0, 0.1);position: relative;z-index: 2}
.post-holder .post-header {position:relative}
.post-holder .post-header .post-info {padding: 0 0 10px 0;}
.post-holder .post-header .post-info .item,
.post-holder .post-header .post-info .dash {display: inline-block}
.post-holder .post-header .post-info .label {font-weight: 700}
.post-holder .post-header .post-info .value {font-style: italic}
.post-content .post-description img {margin:0 15px 0 15px;}
.post-content .post-description ul,
.post-content .post-description ol {list-style-position: inside;}
.post-content .post-description .post-ftimg-hld {float: left; margin: 0 15px 0 15px; width: 33%}
.post-content .post-description .post-ftimg-hld img {width:100%; padding:0px; margin:0px;}
@media (max-width: 496px) {
  .post-content .post-description .post-ftimg-hld {width: 100%; margin:0px;}
}
.widget.block:not(:last-child),
.widget:not(:last-child) {margin-bottom: 40px}
.widget .block-title {margin: 0 0 20px;font-style: normal;font-weight: 400;line-height: 1.42857143;font-size: 1.4rem;}
.widget .block-title strong,
.post-view .block .title strong {font-weight:400}
.widget {clear: both;}
.widget.block-recent-posts .block-content .item {padding: 8px 0 0px 0px;}
.widget.block-categories ul {list-style: initial;padding-left:0px;}
.widget.block-categories ul ul {margin-left:20px;}
.widget.block-categories ul,
.widget.block-categories li {margin: 5px 0 5px 9px;padding: 0px}
.widget.block-rss .rss-icon {float: left; width: 23px; padding-right: 10px;}
/* Tag claud sidebar widget */
.widget.block-tagclaud .smallest{font-size: 0.75em}
.widget.block-tagclaud .small{font-size:1em}
.widget.block-tagclaud .medium{font-size:1.25em}
.widget.block-tagclaud .large{font-size:1.5em}
.widget.block-tagclaud .largest{font-size:2em}
/* Archive sidebar widget */
.widget.block-archive .item {display:inline-block; margin:5px 5px 5px 0; font-size:16px;padding:5px;background-color:#F9F9FF;border: 1px solid #bfbfbf;}

@font-face {
  font-family: montserratMedium;
  src: url("/pub/static/frontend/Oto/oto/en_GB/fonts/Montserrat-Medium.ttf");
  font-display: swap;
}

@font-face {
  font-family: montserratThin;
  font-weight: 700;
  src: url("/pub/static/frontend/Oto/oto/en_GB/fonts/Montserrat-Regular.ttf");
  font-display: swap;
}

@font-face {
  font-family: montserratRegular;
  src: url("/pub/static/frontend/Oto/oto/en_GB/fonts/Montserrat-Regular.ttf");
  font-display: swap;
}



.blog-post-view .page-title-wrapper {
  padding:0 1rem;
}


.blog-post-view .page-title-wrapper h1.page-title {    
    font-family: montserratRegular;
    color: rgba(0, 0, 0, 1);
    letter-spacing: 0.3rem;
    font-size: 20px;
  }

.blog-post-view  .post-holder {background:white;}
.post-content .post-description .post-ftimg-hld {
  margin-bottom:1rem !important;
}


.post-content  .post-description {
  text-align: left;
    text-size-adjust: 100%;
    letter-spacing: 1px;
    font-family: montserratRegular;
    font-size: 14px;
    color: black;
    line-height: 21px;
}

.blog-post-view .product-grid7, .blog-page-list .product-grid7{
  margin-bottom: 2rem;
  padding: 0 0 30px 0;
  background-color: rgb(248, 248, 248);
  width: 300px;
  margin-left: auto;
  margin-right: auto;
}

.blog-post-view  .product-grid7 .title.focus a, .blog-page-list .product-grid7 .title.focus a {
  color: #026974;
  font-family: montserratThin;
}

.blog-post-view  .product-grid7 .title.balance a, .blog-page-list .product-grid7 .title.balance a{
    color: #874680;
    font-family: montserratThin;
}

.blog-post-view .product-grid7 .title.amplify a, .blog-page-list .product-grid7 .title.amplify a{
    color: #ff3e14;
    font-family: montserratThin;
}

.blog-post-view .product-grid7 .product-content .price, .blog-page-list .product-grid7 .product-content .price{
  font-weight: 700;
    font-family: montserratRegular;
    color: black;
}

.blog-post-view .product-grid7 .product-content .box-text-text,
.blog-page-list .product-grid7 .product-content .box-text-text {
  letter-spacing: 1px;
    font-family: montserratRegular;
    font-weight: 400;
    font-size: 14px;
}


.blog-post-view .product-grid7 .product-content  .link-box-main-button a.btn.button-alt, 
.blog-page-list .product-grid7 .product-content  .link-box-main-button a.btn.button-alt{
  background-image: url(/pub/static/frontend/Oto/oto/en_GB/images/balance-background-2.jpg);
    background-size: cover;
    background-color: transparent;
    color: white;
    border: none;
    min-width: 230px;
    border-radius: 0;
    line-height: 22px;
    text-transform: uppercase;
    font-weight: 800;
    padding: 8px 0;
    max-width: 250px;
    text-decoration: none;
    font-size: 10px;
    margin: 0 auto;
    display: block;
    font-size: 12px;
    font-weight: 400;
}

.blog-post-view .product-grid7 .product-content  .link-box-main-button,
.blog-page-list .product-grid7 .product-content  .link-box-main-button {
  margin-top:2rem;
}
.blog-post-view .product-image7 .i-amphtml-layout-size-defined,
.blog-page-list  .product-image7 .i-amphtml-layout-size-defined {
  width: 100% !important;
  height: auto !important;
  min-height:100px;
}

.blog-post-view .product-image7 .i-amphtml-layout-size-defined img,
.blog-page-list  .product-image7 .i-amphtml-layout-size-defined img {
  height: 100%;
  width: 100% !important;
  position: relative;
}

.blog-post-view  .product-content, .blog-page-list  .product-content  {
  margin:1rem 0 2rem;
  text-align:center;
}

.blog-post-view .product-image7 ul.social {
    display: none;
    align-items: center;
    justify-content: center;
  }
.blog-post-view .product-image7 ul.social li {
  text-align: center;
  position: relative;
}

.blog-post-view .product-image7 ul.social li a{
    margin: 0 5px;
    top: 0;
    display: inline-block;
    transform: none;
    position: relative;
    left: 0;
}
.post-view .post-bottom {
  text-align:center;
  display:flex;
  flex-direction:column;
}


.post-view .post-bottom .block.social-share {
  order:1;
}
.post-view .post-bottom .post-nextprev-hld {
  order:2;
  font-family: montserratRegular;
}

.post-view .post-bottom .block.related {
  order:3;
}

.post-view .post-bottom .social-share .amp-social-share-facebook,
.post-view .post-bottom .social-share .amp-social-share-twitter,
.post-view .post-bottom .social-share  .amp-social-share-email {
  background-color:transparent;
  height: 32px !important;
  margin: 0 5px;
  width: 32px !important;
}

.post-view .post-bottom  .social-share .block-title #block-relatedposts-heading {
    letter-spacing: 1px;
    font-family: montserratRegular;
    font-size: 14px;
    color: black;
    line-height: 21px;
    font-weight: 200;
}


.post-view .post-bottom .block-title  #block-relatedposts-heading,
.post-view .post-bottom  .block-title #block-related-heading {
  font-family: montserratThin;
    font-weight: 700;
    line-height: 1.1;
    text-align: center;
    color: black;
    font-size: 24px;
}


.post-view .post-bottom  .block.related .block-content li.item{
  font-size: 13px;
    font-family: montserratRegular;
    margin-bottom: 10px;
    text-transform: uppercase;
    text-align: center;
}

.post-view .post-bottom  .block.related .block-content .products.wrapper .item.product  .product-item-info .product.details a.product-item-link {
  font-size: 14px;
    font-weight: 400;
    text-align: center;
    text-transform: uppercase;
    color: #333333;
    font-family: montserratRegular;
}


.post-view .post-bottom  .block.related .block-content .products.wrapper .item.product  .product-item-info .product.details .price-box {
  margin:7px 0;
}
.post-view .post-bottom  .block.related .block-content .products.wrapper .item.product  .product-item-info .product details .price-box .price-wrapper .price {
  font-size: 14px;
    font-family: montserratRegular;
    font-weight: 700;
    white-space: nowrap;
}

.post-content  .post-description .post-ftimg-hld .i-amphtml-element{
  width: 100% !important;
    height: auto !important;
    min-height: 100px;
}

.post-content  .post-description .post-ftimg-hld .i-amphtml-element img{
  height: 100%;
    width: 100% !important;
    position: relative;
}

.post-view .post-bottom  .product-item-info .product-image-container .product-image-wrapper .product-image-photo {
  width: 100% !important;
    height: auto !important;
    min-height: 100px;
}
.post-view .post-bottom  .product-item-info .product-image-container .product-image-wrapper .product-image-photo img {
  height: 100%;
    width: 100% !important;
    position: relative;
}

.post-view .post-bottom  .block.related .i-amphtml-slides-container {
  position:relative !important;
}

.post-view .post-bottom  .block.related  i-amphtml-sizer {
  padding-top:0 !important;
}

.blog-post-view .widget.block-categories, .blog-page-list  .widget.block-categories  {
  text-align:center;
}

.blog-post-view .widget.block-categories .block-title, .blog-page-list .widget.block-categories .block-title{
  font-family: montserratRegular;
    font-weight: 300;
    line-height: 1.1;
    text-align: center;
    color: black;
    font-size: 24px;
    margin-bottom: 10px;
  }

  .blog-post-view .widget.block-categories ul li a, .blog-page-list .widget.block-categories ul li a {
    font-family: montserratRegular;
    text-transform: uppercase;
    font-size: 13px;
  }

.widget.block-categories ul, .widget.block-categories li {
  list-style:none;
}



.blog-page-list .page-title-wrapper h1.page-title span {
  font-family: montserratRegular;
    color: rgba(0, 0, 0, 1);
    letter-spacing: 0.3rem;
    margin-bottom: 3rem;
}

.blog-page-list .post-holder {
  background:transparent;
}

.blog-page-list .post-holder h2.post-title {
  width: 100%;
    float: none;
    font-family: montserratRegular;
    color: rgba(0, 0, 0, 1);
    line-height: 32px;
    text-align: center;
    max-width: 100%;
    text-transform: none;
}

.blog-page-list .post-holder h2.post-title a {
  color:black;
}


.blog-page-list .post-holder .post-header .post-info {
  display:none;
}

.blog-page-list  .pages-item-next, .blog-page-list .pages-item-previous {
  position:relative;
}

.blog-page-list  .pages-item-next a.action, .blog-page-list .pages-item-previous a.action{
    box-shadow: none;
    border: 0;
    background: 0;
}

.blog-page-list  .toolbar-blog-posts .items.pages-items {
    display: flex;
    align-items: center;
    justify-content: center;
}