<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": [

    {
      "@type": "Question",
      "name": "What is CBD",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "CBD, short for cannabidiol is a non-psycoactive compound found naturally in cannabis plants. A growing body of evidence suggests CBD mayy be helpful in treating pain, anxiety, sleep disorders and fits."
      }
    },
    {
      "@type": "Question",
      "name": "Will CBD get me ‘high’?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "No. The cannabis plant is made up of two main players: CBD and THC. \"CBD is the non-intoxicating portion of the plant, which means that you won't have any effects like euphoria,\" says research academic and CBD expert, Dr Michael Haslam. \"You also won't feel sedated or lose control in any way.\""
      }
    },
    {
      "@type": "Question",
      "name": "Is CBD legal?\n",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "In the UK, pure CBD (CBD isolate) is legal. Products that contain other cannabinoids, like THC, are, however, illegal.\n\nYou may have come across CBD products that are labelled as ‘Full Spectrum’ or ‘Broad Spectrum’. Both of these terms - usually applied to oil products - mean that there are likely other cannabinoids than CBD in the product. As a result, any product with those labels is likely to be technically illegal under current UK law.\n\nThe best way to be sure that a retail product is legal in the UK is to check that the company selling it provides evidence that they only use pure CBD, otherwise known as CBD isolate."
      }
    },
    {
      "@type": "Question",
      "name": "How much CBD do I need?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "In truth, the perfect amount will be different for everyone. Depending on your weight and the unique workings of your endocannabinoid system, the same amount of CBD might affect you differently compared to the next person.\n\nA daily intake of at least 10-20mg CBD can suffice to keep some in your system, but for those who want the most reliable response, an optimum daily intake of 40 -60mg will ensure you are receiving the full benefits. Guidance from the UK’s Food Standard Agency, which suggests a maximum daily intake of 70mg.\n"
      }
    },
    {
      "@type": "Question",
      "name": "Will CBD help me sleep?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "Whilst CBD does not act as a sedative, it can directly affect the level of activity in our brain, which in turn can make it easier for us to fall asleep. Think of it as clearing away the distractions, so your natural sleep cycle can operate at its best.\n\nCBD interacts with serotonin receptors - which play an important role in boosting mood and calming anxiety. CBD also interacts with GABA receptors, which are the main ‘inhibitory’ neurotransmitters in the brain, calming excess activity in the brain and promoting relaxation."
      }
    },
    {
      "@type": "Question",
      "name": "Will CBD help me feel less anxious?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "For the same reasons that CBD can help you fall asleep, when you inhale or swallow CBD it can also help you deal with anxiety.\n\nNot only can it calm anxiety by interacting with serotonin receptors, but CBD can also help prevent the breakdown of anandamide (our internal cannabinoid) by stopping it from being transported to a destructive enzyme.\n\nFor the same reasons that CBD can help you fall asleep, when you inhale or swallow CBD it can also help you deal with anxiety.\n\nNot only can it calm anxiety by interacting with serotonin receptors, as was previously mentioned, but CBD can also help prevent the breakdown of anandamide (our internal cannabinoid) by stopping it from being transported to a destructive enzyme."
      }
    },
    {
      "@type": "Question",
      "name": "Will CBD to help with muscle aches and pains?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "Yes, CBD has been shown to help with aches and pains. There are a few main types of pain, and CBD is best for helping with chronic conditions - those that are long lasting and might be associated with inflammation such as arthritis.\n\nCBD is less helpful for acute pain (the kind you get when you stub your toe or get your fingers caught in a door), but that kind of pain is actually useful for keeping you out of harm’s way! CBD won’t turn you into a painless zombie, it will just help manage those aches that keep you up at night."
      }
    },
    {
      "@type": "Question",
      "name": "Is it possible to overdose on CBD?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "No it is not possible to overdose on CBD. In studies on both animals and people, very large amounts of CBD (thousands of mg) have been used without harm. Excess CBD is naturally removed from our bodies, so the only effect of taking a huge dose of CBD will be an increase in liver activity as it naturally breaks down the molecules."
      }
    },
    
    {
      "@type": "Question",
      "name": "I’ve tried CBD before but I didn’t notice any benefits…",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "Everyone responds to CBD differently. One reason that you don’t notice any benefits might be that your body’s internal systems could already be running at their best. If your endocannabinoid system and other internal regulatory systems are functioning correctly - which means that your body is able to respond quickly and correctly to stresses and other imbalances - then CBD will not change that. Neither will it have any negative effects in those circumstances.\n\nAnother reason for limited benefits may be that the amount of CBD you’re using - the dose - is too low to build up a protective effect in your body. If you’re only taking 5 or 10mg per day, your body might simply be removing it before it has a chance to help you."
      }
    },
    
    {
      "@type": "Question",
      "name": "What is the difference between CBD isolate, full spectrum CBD  and broad spectrum CBD?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "Isolate tends to be nearly pure CBD with trace amounts of other cannabinoids. Full-spectrum contains other cannabinoids including the psychoactive ones like THC and maybe illegal depending on your location. Broad-spectrum contains other cannabinoids, but not THC. However, some of these cannabinoids may be illegal depending on your jurisdiction."
      }
    },
    {
      "@type": "Question",
      "name": "What is the 'Entourage Effect'",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "The entourage effect is the supposed increased efficacy of CBD when other cannabinoids are present. However, the initial study that proposed this effect included THC. A 2020 review showed most studies found no entourage effect, whilst some studies suggested that there might be some adverse reaction. It appears the entourage effect is unfounded marketing hype. "
      }
    },
    {
      "@type": "Question",
      "name": "What is the difference between hemp oil and CBD?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "Hemp oil is made by cold-pressing hemp seeds into an oil that can be used for cooking and contains little or no CBD. CBD oil is extracted from leaves, flowers and stalks of the cannabis plant using carbon dioxide, alcohol or hybrid methods."
      }
    }
  ]
}
</script>