     <section>
 <div class="videoContainer">
	  
        <!-- The parent component -->
<div class="curtain">
	
	
	
	
    <!-- The component wrapper -->
    <div class="curtain__wrapper">
		
	 <div id="video-menu-bar-side">
<ul class="video-button-position" id="video-bar">
<li>
<button title="unmute" class="player-button" id="unmute-button"  ><i class="material-icons">volume_up</i></button>

    
    
    
    
<button title="mute" class="player-button" id="mute-button"  ><i class="material-icons">volume_off</i></button>
</li>
<li>
<button title="pause"  class="player-button" id="pause-button" >SKIP</button>
<button title="play"  class="player-button" id="play-button" ><i class="material-icons">play_circle_outline</i></button>
</li>

</ul>

</div>
            <input type="checkbox" id="videocheck" checked onchange="doalert(this)">
      
      <!-- The left curtain panel -->
      <div class="curtain__panel curtain__panel--left">
  
      </div> <!-- curtain__panel -->
      
      <!-- The prize behind the curtain panels -->
      <div class="curtain__prize">

            <div class="video-wrapper">

                    <video autoplay  muted  playsinline class="fillWidth homepage-video" id="introVideo"    >
                     
                       
                
                
                
                
                          </video>
                          </div>
                
  
      </div> <!-- curtain__prize -->
      
      <!-- The right curtain panel -->
      <div class="curtain__panel curtain__panel--right">
          
      </div> <!-- curtain__panel -->
      
    </div> <!-- curtain__wrapper -->
    <a href="#shero-slider" class="scroller"><span></span></a>
  </div> <!-- curtain -->


 </div>
         </section>
