 <main >
             <div class="container-fluid">
              
                         <div class=" row topMargin standard-no-bottom">
                       
                           <div class="col-sm-12 uppercase-copy"><h1>Need to get in touch?</h1>
                             </div>
                            </div>

								<div class="row  standard-padding-adjust-no-bottom">
                                    
									<div class="col-lg-6">
									<p>Fill in our contact form or email us at <a href="mailto:info@otocbd.com"> info@otocbd.com.</a></p>
                                        <div class="top-bottom-4">
										<p class="find-your-space">We can help if you: </p>
										
											<ul class="contact-list" style="list-style-type: disc;">
                                       
										<li>want to know more about OTO products</li>
												<li>have a question about CBD or any other ingredients</li>
										
                                                <li>need help with an order or customer query/issue</li>
                                                <li>want to take part in our consumer trials</li>
<li>are considering stocking OTO products</li>
							<li>have a press or marketing enquiry</li>
										</ul>
                                            </div>
										<p>
								We will get back to you as quickly as possible.</p>
                               <!-- <h2 class="contact-press">For press or marketing enquiries:</h2>
<p>please email Hayley at <a href="mailto:hj@otocbd.com">hj@otocbd.com</a></p>-->
									</div>
									<div class="col-lg-6 form-holder">
                                 <?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \Magento\Contact\Block\ContactForm $block */
?>
<form class="form contact"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
       
        <div class="field name required">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field telephone">
            <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="control">
                <input name="telephone" id="telephone" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text" />
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="comment"><span><?= $block->escapeHtml(__('What’s on your mind?')) ?></span></label>
            <div class="control">
                <textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>

										
										
										
										
								
								
								</div>
							</div>
				  
				
				  
				  <div class="row  standard-contact-bottom">
					  <div class="col-lg-8">
                      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2484.0792090249483!2d-0.22186258427722833!3d51.493413919546846!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48760f64849229f9%3A0xca21326508c896ed!2sOTO%20CBD!5e0!3m2!1sen!2suk!4v1580911824621!5m2!1sen!2suk" width="100%" height="450" frameborder="0" style="border:none;" allowfullscreen=""></iframe>
					


					  </div> <div class="col-lg-4 form-holder">
					  <h4>OTO International Ltd</h4>
                      <p>1 Lyric Square<br />
                      Hammersmith<br />
						  London<br />
						  W6 0NB
                      </p>
                      <h4>0203-963 5955</h4>
                      <h4><a href="mailto:support@otocbd.com">support@otocbd.com</a></h4>
							  </div></div>
					


					</main>
