<?php

$product = $block->getProduct();

?>



<p class="testimonial-quote"><?php echo $product->getData('testimonial_quote_1'); ?></p>

<p class="testimonial-author"><?php echo $product->getData('testimonial_author_1'); ?></p>
<p class="testimonial-quote"><?php echo $product->getData('testimonial_quote_2'); ?></p>
<p class="testimonial-author"><?php echo $product->getData('testimonial_author_2'); ?></p>
<p class="testimonial-quote"><?php echo $product->getData('testimonial_quote_3'); ?></p>
<p class="testimonial-author"><?php echo $product->getData('testimonial_author_3'); ?></p>
<p class="testimonial-quote"><?php echo $product->getData('testimonial_quote_4'); ?></p>
<p class="testimonial-author"><?php echo $product->getData('testimonial_author_4'); ?></p>