<?php
// @codingStandardsIgnoreFile
?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>
<?php if ($block->displayProductStockStatus()) : ?>
    <?php if ($_product->isAvailable()) : ?>
        <div class="stock available" title="<?php /* @noEscape */ echo __('Availability') ?>">
            <span><?php /* @noEscape */ echo __('In stock') ?></span>
        </div>
    <?php else : ?>
        <div class="stock unavailable" title="<?php /* @noEscape */ echo __('Availability') ?>">
            <span><?php /* @noEscape */ echo __('Out of stock') ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
