<?php
/**
* Copyright © 2013-2017 Magento, Inc. All rights reserved.
* See COPYING.txt for license details.
*/
// @codingStandardsIgnoreFile
/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Bag');

$fixclass= __('subscribe-off');
$subsid = $_product->getId();
$subproduct = $_product->getData('subscription_url');
$subtext = $_product->getData('subscription_text');
$subenabled = $_product->getData('subscription_enabled');




 $stockItem = $_product->getExtensionAttributes()->getStockItem()->getQty();
$stockists = $_product->getData('alternative_stockists');
if (($stockItem<1)&&($_product->getTypeId() == 'simple')){
    $buttonTitle = __('Pre-Order');

}




if (($stockItem<1)&&(!empty($stockists))) : ?>

<div class="alternative-stockists">
<?php
echo $stockists;


?>

</div>
<?php
 elseif ($_product->isSaleable()): ?>
<div class="box-tocart">
   <div class="fieldset">

   <div class="actions">

 


           <button type="submit"
                   title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                   class="action primary tocart"
                   id="product-addtocart-button"
                 >
               <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
           </button>
           <?php echo $block->getChildHtml('', true) ?>
       </div>

       <?php if ($block->shouldRenderQuantity()): ?>
       <div class="field qty">
           <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>

            <script type="text/x-magento-init">
{
   "*": {
           "Magento_Ui/js/core/app": {
               "components": {
                   "qty_change": {
                       "component": "Oto_Plusminus/js/view/product/view/qty_change",
                       "defaultQty": <?php echo $block->getProductDefaultQty() * 1 ?>
                   }
               }
           }
   }
}
</script>

<div class="control" data-bind="scope: 'qty_change'">
   <button data-bind="click: decreaseQty">-</button>
   <input  data-bind="value: qty()"
   type="number"
   name="qty"
   id="qty"
   maxlength="12"
   title="<?php echo __('Qty') ?>"
   class="input-text qty"
   data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
   />

   <button data-bind="click: increaseQty">+</button>
</div>
       </div>
       <?php endif; ?>
      
   </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
   {
       "#product_addtocart_form": {
           "Magento_Catalog/product/view/validation": {
               "radioCheckboxClosest": ".nested"
           }
       }
   }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
   {
       "#product_addtocart_form": {
           "catalogAddToCart": {
               "bindSubmit": false
           }
       }
   }
</script>
<?php endif; ?>


<?php if ($subenabled ==1) : ?>


<div class="subscribe-row"> 
<script src="https://js.chargebee.com/v2/chargebee.js" data-cb-site="otocbd" data-cb-gtm-enabled="true" ></script>
<div class="subscribe-holder">    
<p><button onclick="javascript:void(0)" data-cb-type="checkout" data-cb-item-0="Sleep-Drops-GBP-Monthly" class="action primary tocart" id="subscribe-button">
<span> <?php echo $subtext ?></span>
</button></p>
</div> <div class="control-two"> </div> </div>

<script>
document.addEventListener("DOMContentLoaded", function() {
var cbInstance = Chargebee.getInstance();
var link = document.querySelectorAll("[data-cb-type=checkout]")[0];
var product = cbInstance.getProduct(link);
product.addCoupon("FIRSTMONTHDISCOUNT");
});
</script>


<?php else : ?>

 <?php endif; ?>

  
<style>

.balance #subscribe-button{color:#330072;background:white;background-color:white;border: 1px solid #330072;}


    @media only screen and (min-width: 768px) {

.product-info-main .box-tocart .actions, .subscribe-holder  {padding-left:0px}
.subscribe-holder {margin-top:10px}
    }


 @media only screen and (max-width: 767px) {
#subscribe-button {
  width: calc(100vw - 75px);
  margin-left: 50px;
  margin-right: 50px;
  color: #fff;
  margin-top: 20px;
  min-width: 0%;
}

.product-info-main .box-tocart{margin-top:0}

 }

</style>
